
[project]
name = "bitstring"
version = "4.0.0.b3"
authors = [
  { name="Scott Griffiths", email="dr.scottgriffiths@gmail.com" },
]
description = "Simple construction, analysis and modification of binary data."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

keywords = ["binary", "bitarray", "bitvector"]

[project.urls]
homepage = "https://github.com/scott-griffiths/bitstring"
documentation = "https://bitstring.readthedocs.io/en/latest/"